name: Jest

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  make-test:
    # Name the Job
    name: Runs tests
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      
      # installing dependencies
      - name: Install Dependencies
        run: make install
        # Add environment variables
        env:
          CI: true

      # Runs the Linter action
      - name: Run tests
        run: make test

      # Publish code coverage on Code Climate
      # https://github.com/paambaati/codeclimate-action
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
